---
title: "Chapter 7: Introduction to Bayesian Time Series Analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Chapter 7: Introduction to Bayesian Time Series Analysis}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 8,
  fig.height = 6
)
knitr::opts_knit$set(global.par = TRUE)
pdfplots <- FALSE # default: FALSE; set this to TRUE only if you like pdf figures
```

```{r, include = FALSE}
par(mgp = c(1.6, .6, 0), mar = c(2.6, 2.6, 2.6, .4), lwd = 1)
```

# Section 7.2
## Figure 7.1
First, we load the data. Because of the extreme outliers during the COVID
pandemic, we restrict our analysis to the time before its outbreak.

```{r}
data("gdp", package = "BayesianLearningCode")
dat <- gdp[1:which(names(gdp) == '2019-10-01')]
```

Next, we compute the percentage log returns.

```{r}
y <- 100 * (log(dat[-1]) - log(dat[-length(dat)]))
```

Now we can plot the data and its empirical autocorrelation function.

```{r, echo = -c(1:2)}
if (pdfplots) {
  pdf("7-2_1.pdf", width = 8, height = 5)
  par(mar = c(2.5, 1.5, .1, .1), mgp = c(1.5, .5, 0))
}
par(mfrow = c(1,2))
ts.plot(y, main = "U.S. GDP percentage log returns")
acf(y, lag = 6, main = "")
title("Empirical autocorrelation function")
```
